"""Generates every CycleCare brand SVG from one set of geometry constants.

Run from the repo root:  python tool/brand/generate_svg.py
Outputs to assets/brand/.
"""

from __future__ import annotations

import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))

import brand as B  # noqa: E402

OUT_DIR = Path(__file__).resolve().parents[2] / "assets" / "brand"

HEADER = "<!-- Generated by tool/brand/generate_svg.py - do not edit by hand. -->"


def _svg(body: str, width: float, height: float, view: str | None = None) -> str:
    view = view or f"0 0 {width:g} {height:g}"
    return (
        f'<svg xmlns="http://www.w3.org/2000/svg" viewBox="{view}" '
        f'width="{width:g}" height="{height:g}" fill="none" '
        f'role="img" aria-label="CycleCare">\n{HEADER}\n{body}\n</svg>\n'
    )


def _rose_gradient(gid: str = "rose") -> str:
    """The app's menstrualGradient, topLeft -> bottomRight."""
    return (
        f'<linearGradient id="{gid}" x1="0" y1="0" x2="1" y2="1">'
        f'<stop offset="0" stop-color="{B.ROSE}"/>'
        f'<stop offset="1" stop-color="{B.ROSE_LIGHT}"/>'
        "</linearGradient>"
    )


def _mark_body(
    ring_paint: str,
    heart_paint: str,
    dot_paint: str,
    phases: bool = False,
) -> str:
    """The mark's drawing instructions, in a 512 coordinate space."""
    dx, dy = B.dot_center()
    parts: list[str] = []

    if phases:
        for path, color in zip(B.phase_arcs(), B.PHASE_COLORS):
            parts.append(
                f'<path d="{path}" stroke="{color}" stroke-width="{B.RING_W:g}" '
                'stroke-linecap="round"/>'
            )
    else:
        parts.append(
            f'<path d="{B.ring_path()}" stroke="{ring_paint}" '
            f'stroke-width="{B.RING_W:g}" stroke-linecap="round"/>'
        )

    parts.append(f'<circle cx="{dx:g}" cy="{dy:g}" r="{B.DOT_R:g}" fill="{dot_paint}"/>')
    parts.append(
        f'<path d="{B.HEART_PATH}" transform="{B.heart_transform()}" '
        f'fill="{heart_paint}"/>'
    )
    return "\n".join("  " + p for p in parts)


# ── Marks ────────────────────────────────────────────────────────────────────
def mark_primary() -> str:
    body = f"  <defs>{_rose_gradient()}</defs>\n" + _mark_body(
        ring_paint="url(#rose)", heart_paint=B.ROSE_DARK, dot_paint=B.ROSE
    )
    return _svg(body, B.SIZE, B.SIZE)


def mark_phases() -> str:
    body = _mark_body(
        ring_paint="", heart_paint=B.INK, dot_paint=B.ROSE, phases=True
    )
    return _svg(body, B.SIZE, B.SIZE)


def mark_white() -> str:
    body = _mark_body(ring_paint=B.WHITE, heart_paint=B.WHITE, dot_paint=B.WHITE)
    return _svg(body, B.SIZE, B.SIZE)


def mark_mono() -> str:
    body = _mark_body(ring_paint=B.INK, heart_paint=B.INK, dot_paint=B.INK)
    return _svg(body, B.SIZE, B.SIZE)


# ── App icon ─────────────────────────────────────────────────────────────────
def app_icon(size: int = 1024, squircle_r: int = 230) -> str:
    """Rose tile with the mark knocked out in white - the launcher icon."""
    inner = _mark_body(ring_paint=B.WHITE, heart_paint=B.WHITE, dot_paint=B.WHITE)
    body = (
        f"  <defs>{_rose_gradient('tile')}</defs>\n"
        f'  <rect width="{size}" height="{size}" rx="{squircle_r}" fill="url(#tile)"/>\n'
        f'  <g transform="{B.scale_to(size * 0.645, size)}">\n{inner}\n  </g>'
    )
    return _svg(body, size, size)


def app_icon_foreground(size: int = 1024) -> str:
    """Android adaptive-icon foreground: transparent, white mark, no background.

    flutter_launcher_icons wraps this in `<inset android:inset="16%"/>`, which
    already reserves the adaptive safe zone - so the mark fills 92% of its own
    canvas here and lands at ~63% of the 108dp adaptive canvas once inset.
    """
    inner = _mark_body(ring_paint=B.WHITE, heart_paint=B.WHITE, dot_paint=B.WHITE)
    body = f'  <g transform="{B.scale_to(size * 0.92, size)}">\n{inner}\n  </g>'
    return _svg(body, size, size)


def app_icon_square(size: int = 1024) -> str:
    """Full-bleed square tile. iOS and Android apply their own corner masks."""
    return app_icon(size, squircle_r=0)


def app_icon_round(size: int = 1024) -> str:
    """Circular tile for Android's ic_launcher_round."""
    return app_icon(size, squircle_r=size // 2)


def app_icon_maskable(size: int = 512) -> str:
    """PWA maskable icon: full bleed, artwork inside the centred 80% safe circle."""
    inner = _mark_body(ring_paint=B.WHITE, heart_paint=B.WHITE, dot_paint=B.WHITE)
    body = (
        f"  <defs>{_rose_gradient('tile')}</defs>\n"
        f'  <rect width="{size}" height="{size}" fill="url(#tile)"/>\n'
        f'  <g transform="{B.scale_to(size * 0.56, size)}">\n{inner}\n  </g>'
    )
    return _svg(body, size, size)


# ── Wordmarks ────────────────────────────────────────────────────────────────
WORDMARK_H = 180
WORDMARK_MARK_SPAN = 132.0
WORDMARK_GAP = 34.0
WORDMARK_FONT_SIZE = 108
WORDMARK_BASELINE = 128
WORDMARK_TRACKING = -2.5


def _wordmark(text_fill: str, accent_fill: str, width: float) -> str:
    scale = WORDMARK_MARK_SPAN / B.ART_SPAN
    tx = -B.ART_MIN * scale
    ty = (WORDMARK_H - WORDMARK_MARK_SPAN) / 2 - B.ART_MIN * scale
    text_x = WORDMARK_MARK_SPAN + WORDMARK_GAP

    inner = _mark_body(
        ring_paint="url(#rose)", heart_paint=B.ROSE_DARK, dot_paint=B.ROSE
    )
    style = B.font_face_css()

    return _svg(
        f"  <defs>{_rose_gradient()}</defs>\n"
        f"  <style>{style}</style>\n"
        f'  <g transform="translate({tx:.3f} {ty:.3f}) scale({scale:.5f})">\n'
        f"{inner}\n  </g>\n"
        f'  <text x="{text_x:g}" y="{WORDMARK_BASELINE}" '
        f'font-family="Nunito" font-weight="800" font-size="{WORDMARK_FONT_SIZE}" '
        f'letter-spacing="{WORDMARK_TRACKING}" fill="{text_fill}">'
        f'Cycle<tspan fill="{accent_fill}">Care</tspan></text>',
        width,
        WORDMARK_H,
    )


def wordmark_light(width: float) -> str:
    return _wordmark(B.INK, B.ROSE, width)


def wordmark_dark(width: float) -> str:
    return _wordmark(B.DARK_TEXT, B.ROSE_LIGHT, width)


# ── Social preview (GitHub repo card: 1280x640) ──────────────────────────────
SOCIAL_W, SOCIAL_H = 1280, 640


def social_preview() -> str:
    style = B.font_face_css()
    mark_span = 116.0
    scale = mark_span / B.ART_SPAN
    mark_x = 96 - B.ART_MIN * scale
    mark_y = 96 - B.ART_MIN * scale
    inner = _mark_body(
        ring_paint="url(#rose)", heart_paint=B.ROSE_DARK, dot_paint=B.ROSE
    )

    chips = [
        ("Menstrual", B.ROSE),
        ("Follicular", B.FOLLICULAR),
        ("Ovulation", B.OVULATION),
        ("Luteal", B.LUTEAL),
    ]
    chip_svg: list[str] = []
    cx = 96.0
    for label, color in chips:
        w = 24 + len(label) * 11.2 + 24 + 18
        chip_svg.append(
            f'<g transform="translate({cx:.1f} 508)">'
            f'<rect width="{w:.1f}" height="52" rx="26" fill="{color}" fill-opacity="0.16"/>'
            f'<circle cx="26" cy="26" r="8" fill="{color}"/>'
            f'<text x="46" y="34" font-family="Nunito" font-weight="700" '
            f'font-size="21" fill="{B.on_light(color)}">{label}</text>'
            "</g>"
        )
        cx += w + 16

    # Oversized ring echo on the right, clipped by the canvas edge.
    echo_scale = 470 / B.ART_SPAN
    echo = (
        f'<g transform="translate({1010 - B.CX * echo_scale:.1f} '
        f'{320 - B.CY * echo_scale:.1f}) scale({echo_scale:.5f})" opacity="0.10">'
        f'<path d="{B.ring_path()}" stroke="{B.ROSE}" stroke-width="{B.RING_W:g}" '
        'stroke-linecap="round"/>'
        f'<circle cx="{B.dot_center()[0]:g}" cy="{B.dot_center()[1]:g}" '
        f'r="{B.DOT_R:g}" fill="{B.ROSE}"/>'
        f'<path d="{B.HEART_PATH}" transform="{B.heart_transform()}" fill="{B.ROSE}"/>'
        "</g>"
    )

    body = (
        f"  <defs>{_rose_gradient()}"
        f'<radialGradient id="glow" cx="0.5" cy="0.5" r="0.5">'
        f'<stop offset="0" stop-color="{B.ROSE}" stop-opacity="0.20"/>'
        f'<stop offset="1" stop-color="{B.ROSE}" stop-opacity="0"/>'
        "</radialGradient>"
        f'<radialGradient id="glow2" cx="0.5" cy="0.5" r="0.5">'
        f'<stop offset="0" stop-color="{B.FERTILE}" stop-opacity="0.16"/>'
        f'<stop offset="1" stop-color="{B.FERTILE}" stop-opacity="0"/>'
        "</radialGradient></defs>\n"
        f"  <style>{style}</style>\n"
        f'  <rect width="{SOCIAL_W}" height="{SOCIAL_H}" fill="{B.CREAM}"/>\n'
        f'  <circle cx="1180" cy="70" r="420" fill="url(#glow)"/>\n'
        f'  <circle cx="70" cy="620" r="340" fill="url(#glow2)"/>\n'
        f"  {echo}\n"
        f'  <g transform="translate({mark_x:.3f} {mark_y:.3f}) scale({scale:.5f})">\n'
        f"{inner}\n  </g>\n"
        f'  <text x="240" y="188" font-family="Nunito" font-weight="800" font-size="86" '
        f'letter-spacing="-2" fill="{B.INK}">Cycle<tspan fill="{B.ROSE}">Care</tspan></text>\n'
        f'  <text x="96" y="316" font-family="Nunito" font-weight="800" font-size="52" '
        f'letter-spacing="-1" fill="{B.INK}">Your cycle, your way.</text>\n'
        f'  <text x="96" y="378" font-family="Nunito" font-weight="600" font-size="29" '
        f'fill="{B.MUTED}">Menstrual health, fertility and wellness tracking that stays</text>\n'
        f'  <text x="96" y="420" font-family="Nunito" font-weight="600" font-size="29" '
        f'fill="{B.MUTED}">on your device. Offline-first, ad-free, open source.</text>\n'
        f'  {"".join(chip_svg)}\n'
        f'  <text x="96" y="606" font-family="Nunito" font-weight="700" font-size="22" '
        f'fill="{B.MUTED}" opacity="0.85">Flutter &#183; Riverpod &#183; Material 3 &#183; MIT licensed</text>'
    )
    return _svg(body, SOCIAL_W, SOCIAL_H)


# ── Entry point ──────────────────────────────────────────────────────────────
# Measured in Chrome via measure_wordmark.py; falls back to an estimate.
WORDMARK_WIDTH_FILE = Path(__file__).resolve().parent / "_wordmark_width.txt"


def wordmark_width() -> float:
    if WORDMARK_WIDTH_FILE.exists():
        return float(WORDMARK_WIDTH_FILE.read_text().strip())
    return 720.0


def main() -> None:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    if not B.has_fonts():
        print("WARNING: Nunito not found in tool/fonts - wordmark text will not embed")

    width = wordmark_width()
    files = {
        "cyclecare-mark.svg": mark_primary(),
        "cyclecare-mark-phases.svg": mark_phases(),
        "cyclecare-mark-white.svg": mark_white(),
        "cyclecare-mark-mono.svg": mark_mono(),
        "cyclecare-icon.svg": app_icon(),
        "cyclecare-icon-foreground.svg": app_icon_foreground(),
        "cyclecare-wordmark.svg": wordmark_light(width),
        "cyclecare-wordmark-dark.svg": wordmark_dark(width),
        "cyclecare-social-preview.svg": social_preview(),
    }
    for name, content in files.items():
        (OUT_DIR / name).write_text(content, encoding="utf-8")
        print(f"wrote {name} ({len(content)} bytes)")


if __name__ == "__main__":
    main()
