name: cyclecare_flutter
description: CycleCare, a privacy-first menstrual cycle tracker for iOS and Android.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'
  flutter: '>=3.16.0'

dependencies:
  flutter:
    sdk: flutter

  flutter_riverpod: ^2.4.9

  shared_preferences: ^2.2.2

  cupertino_icons: ^1.0.6
  intl: ^0.18.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
